<?php
namespace Home\Controller;
use Common\Controller\CommonController;
class BianjbController extends CommonController {
    protected $MENU_INDEX = 4;
    protected $MENU_INDEX_MOBILE = 2;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        parent::setMenu($this->MENU_INDEX);
        parent::setMobileMenu($this->MENU_INDEX_MOBILE);

    }
    public function index(){
        $this->display();
    }
    public function login(){
        $this->display();
    }
    public function register(){
        $this->display();
    }
}