<?php
namespace Home\Controller;
use Common\Controller\CommonController;
class GuajbController extends CommonController {
    protected $MENU_INDEX = 2;
    protected $MENU_INDEX_MOBILE = 2;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        parent::setMenu($this->MENU_INDEX);
        parent::setMobileMenu($this->MENU_INDEX_MOBILE);

    }

    public function index(){
        $this->display();
    }

}