<?php
namespace Home\Controller;

use Common\Controller\CommonController;

class IndexController extends CommonController{
    protected $MENU_INDEX_MOBILE = 1;
    protected $MENU_INDEX = 1;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        parent::setMobileMenu($this->MENU_INDEX_MOBILE);
        parent::setMenu($this->MENU_INDEX);

    }
    public function index(){
        $this->display();
    }

    public function register(){
        if(IS_AJAX){
            $model = D('SysUser');
            $user = $model->where(array('account'=>$_REQUEST['account']))->find();
            if(empty($user)){
               $result =  $model->register($_REQUEST);
            }
            if(is_numeric($result['id'])){
                $return['status'] = 1;
                $return['msg'] = '注册成功';
                $model->autoLogin($result);
            }else{
                $return['status'] = 0;
                $return['msg'] = $result;
            }
            $this->ajaxReturn($return);
        }else{
            $this->display();
        }

    }
}